### ISSUE TITLE
uninitialized constant JsonSchema::Api 

### ISSUE THREAD

**Issue by erikjenks** [alex-zige/rails_on_rails#5]
Hey man I really appreciate this app. It's what I've been looking for for a few days. I followed your commits leaving out some of the things that aren't applicable to me, but I received a few errors while running the tests. 

``` ruby
1) Api::V1::SessionsController POST create with valid params json matches the schema
     Failure/Error: expect(json).to match_response_schema JsonSchema::Api::V1.current_user
     NameError:
       uninitialized constant JsonSchema::Api
# ./spec/controllers/api/v1/sessions_controller_spec.rb:45:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:23:in `block (3 levels) in <top (required)>'
     # /Users/jenks/.gem/ruby/2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/jenks/.gem/ruby/2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # /Users/jenks/.gem/ruby/2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/jenks/.gem/ruby/2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:87:in `call'
     # /Users/jenks/.gem/ruby/2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:22:in `block (2 levels) in <top (required)>'

```

I am receiving that one in all three specs. I looked in the files that are used for the Json-Schema gem but can't seem to find the issue. Any idea?

**Comment by erikjenks** [comment]
Fixed. I had the JSON schema in the wrong path.

**Comment by alex-zige** [comment]
Thanks man, good to know you liked this project. The main goal of this project is to DRY the processes we have in every new rails api project.  Hope it could save you some time as well :smile:  
Let us know if you have any other issues, we'd like to help :+1:  
cc @cameronbourgeois
