### ISSUE TITLE
401 Unauthorized on sign_out

### ISSUE THREAD

**Issue by erikjenks** [alex-zige/rails_on_rails#7]
Using the following cURL method I am receiving a 401-unauthorized when attempting to sign out from the API.

``` ruby
curl -v -H "Accept: application/json" -H "Content-type: application/json" -X DELETE -d ' {"user":{"email":"email@email.com","password":"12345678"}}'  http://localhost:3000/api/sign_out
```

Here are my routes:

``` ruby
Rails.application.routes.draw do
  # devise_for :users
  namespace :api, :defaults => {:format => :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        post "sign_up", to: 'registrations#create'
        post "sign_in", to: 'sessions#create'
        delete "sign_out", to: 'sessions#destroy'
        # post "password/reset", to: 'passwords#create' ### WIP
        resources :users, only: [:show, :update]
      end
    end
  end
```

And my session_controller destroy method

``` ruby
  def destroy
    if @current_user.reset_authentication_token
      render nothing: true
    else
      render json: {error: @current_user.errors}, status: :unprocessable_entity
    end
  end
```

Again I followed your example, but not sure why this is doing this?

**Comment by alex-zige** [comment]
hey @erikjenks, the sessions_contorllers uses authentication_token to authenticate users. Once logged in, you should receive the authentication for current user for all subsequences requests. 

You don't need pass the user email/password to `DELETE` sign_out, instead you could do

```
 $ curl -H "Authorization:your-user-authentication-token"  -X DELETE http://localhost:3000/api/sign_out
```

**Comment by erikjenks** [comment]
Thanks. I appreciate it. That works.

**Comment by alex-zige** [comment]
Awesome.Good to know. probably need better docs :+1:

**Comment by erikjenks** [comment]
one thing I forgot to add before I closed it was that instead of passing `Authorization` I had to curl like so:

``` ruby
curl -H "authentication_token":"TOKEN HERE"  -X DELETE http://localhost:3000/api/sign_out
```

**Comment by alex-zige** [comment]
nice one @erikjenks.
will update the doc soon to avoid any confusion later :smile:

**Comment by alex-zige** [comment]
hey @erikjenks, you might wanna take a look this https://github.com/alex-zige/rails_on_rails/pull/10
